server:
  port: 8888

---
security:
  user:
    name: mutou
    password: 701712

---
#encrypt:
#  keyStore:
#    location: classpath:/server.jks
#    password: letmein  # storepass
#    alias: mytestkey    # alias
#    secret: changeme   # keypass
#  fail-on-error: false
encrypt:
  key: foo

---
#改变url访问路径
management:
  context-path: /admin

---
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:1111/eureka/,http://eureka-server2:1112/eureka/,http://eureka-server3:1113/eureka/
  instance:
    prefer-ip-address: true
    health-check-url-path: /admin/health #查看健康运行状态
    status-page-url-path: /admin/info

---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xinxiamu/ymu-special-selling.git
          search-paths: spcselling-config/spcselling-config-repo
#          username:
#          password:

---
# spring-cloud-bus刷新配置
spring:
  rabbitmq:
    host: 119.23.78.160
    port: 5672
    username: zmt
    password: 701712
    virtual-host: /