spring:
  application: 
    name: config-server

---
spring: 
  profiles:
    active: dev-server1 #启动三个做负载均衡
#    active: dev-server2
#    active: dev-server3
      
---
#访问测试：http://localhost:8888/syssms/dev/master 规则/{application}/{profile}[/{label}]
#指向同一个git仓库
spring: 
  cloud:
    config: 
      server: 
        git:
          uri: https://github.com/xinxiamu/ymu-special-selling.git
          searchPaths: spcselling-config/spcselling-config-repo
#          username: xinxiamu
#          password: wnt*ZMT*701712%%      

      
      
    
        
          