server:
  port: 8888

---
security:
  user:
    name: admin
    password: 123456

---
#改变url访问路径
#management:
#  context-path: /admin

---
#作为服务注册到注册中心
eureka:
  instance:
#    prefer-ip-address: false
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka/
#    health-check-url-path: /admin/health #查看健康运行状态
#    status-page-url-path: /admin/info

---
#git配置中心
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xinxiamu/ymu-special-selling.git
          search-paths: spcselling-config/spcselling-config-repo


---
# spring-cloud-bus刷新配置
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: spcs
    password: spcs
    publisher-confirms: true
    virtual-host: /