server:
  port: 9001
  ssl:
    key-store: ${user.dir}/ssl-keys-dev.jks
    key-store-password: 701712
    key-password: 701712

---
custom:
  tomcat:
    http:
      port: 9000 # http端口
    redirect-flg: false # false表示打开http端口时不自动跳转到https

---
spring:
  datasource: #数据库配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      spcs-user: # 会员主库
        url: jdbc:mysql://localhost:3307/spcs_user?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useFastDateParsing=false&pinGlobalTxToPhysicalConnection=true&serverTimezone=CST
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 1
        minIdle: 1
        maxActive: 50
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
      spcs-user-slave: #会员从库
        url: jdbc:mysql://localhost:3307/spcs_user_slave?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useFastDateParsing=false&pinGlobalTxToPhysicalConnection=true&serverTimezone=CST
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 1
        minIdle: 1
        maxActive: 50
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
#      filters: wall,stat,log4j2 #改为在代码中定制配置
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: config.decrypt=true;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

---
druid:
  login-user-name: admin
  login-user-pwd: admin
  allow: 192.168.1.69 #ip白名单
  deny: 192.168.1.68 #ip黑名单

---
spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true

---
logging:
  config: classpath:dev/log4j2.xml

---
# cors跨域设置
custom:
  cors:
    mapping: /**
    allowCredentials: false
    allowedOrigins: * #允许的域，多个用逗号隔开。*允许全部的域通过
    allowedMethods: POST,GET,DELETE,PUT
    allowedHeaders: *


---
### redis,rabbitmq
#spring:
#  profiles: redis-config-dev,rabbitmq-config-dev

---
#redis
spring:
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 10 # 连接超时时间（毫秒）

---
#rabbitMq
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: spcs
    password: spcs
    publisher-confirms: true
    virtual-host: /