server:
  port: 9001

---
spring:
  rabbitmq:
    host: 119.23.78.160
    port: 5672
    username: zmt
    password: 701712
    virtual-host: /

---
spring:
  datasource: #数据库配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      spcs-user: # 会员主库
        url: jdbc:mysql://localhost:3307/spcs_user?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useFastDateParsing=false&pinGlobalTxToPhysicalConnection=true&serverTimezone=CST
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 1
        minIdle: 1
        maxActive: 50
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
      spcs-user-slave: #会员从库
        url: jdbc:mysql://localhost:3307/spcs_user_slave?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useFastDateParsing=false&pinGlobalTxToPhysicalConnection=true&serverTimezone=CST
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 1
        minIdle: 1
        maxActive: 50
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
#      filters: wall,stat,log4j2 #改为在代码中定制配置
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: config.decrypt=true;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

---
druid:
  login-user-name: admin
  login-user-pwd: admin
  allow: 192.168.1.69 #ip白名单
  deny: 192.168.1.68 #ip黑名单

---
spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true

---
logging:
  config: classpath:dev/log4j2.xml