server:
  port: 8001 # https端口
  ssl:
      key-store: ${user.dir}/ssl-keys-dev.jks
      key-store-password: 701712
      key-password: 701712

---
custom:
  tomcat:
    http:
      port: 8000 # http端口
    redirect-flg: false # false表示打开http端口时不自动跳转到https

#---
#spring:
#  cloud:
#    config:
#      username: admin
#      password: 123456

---
#eureka: #服务注册
#  instance:
##    prefer-ip-address: true
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:1111/eureka/

---
logging:
  config: classpath:dev/log4j2.xml

---
# cors跨域设置
custom:
  cors:
    mapping: /**
    allowCredentials: false
    allowedOrigins: "*" #允许的域，多个用逗号隔开。*允许全部的域通过。一定要用双引号，否则配置文件报错。
#    allowedMethods: POST,GET,DELETE,PUT #这样设置，静态资源将不能跨域
    allowedMethods: "*"
    allowedHeaders: "*"

---
### redis,rabbitmq
#spring:
#  profiles:
#    include: redis-config-dev,rabbitmq-config-dev

---
#redis
spring:
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 10 # 连接超时时间（毫秒）

---
#rabbitMq
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: spcs
    password: spcs
    publisher-confirms: true
    virtual-host: /