info:
  from: git
  name: syssms
  profile: dev
  pwd: '{cipher} 24250AQBGV8foGbss9bO6J2+C46G6GmIrFR0IsUPILunHhCJq33L1Xus5zGiituFHnvovIzuN2JdRR+NnyDnshTES5hX5ZuGQZ3bEAaNDZ6G3sYmrcet9C8uCb4SPwhbWQF7gU7lY+jVLvIKcFFO3FgAcVveyhrZv8Qb0aeKsHbKJJDYviUc1la29n/Vhq+9CpbvgoG66U/BTGb9eKLVOBPO9UOvZoIqLm7KsYRFxKEvSX2RBMz5FRvMilnBfs/U/hO4b3+69yVhoYRD1/At2jWSJRZ+6lNSzMAHRZ6OsIjSN69KyCW4qFfy0g3GtHz5OKfCRjFaRKqWfoG2nCM9FKcN+HBzGZrXVWLEUK41VgqQj5wxI2LdBbYWF+Kx6StvrqLkoIqE='

spring:
  datasource:
    username: dbuser
    password: '{cipher}1920AQA6re35UlLsM+a0z4LUcJVMQzA5+jU1mIXnZvLZUrO06jh1jTBfcqVQFCBTnKRfST0+PLGUInSh01Yyy50gXJhLz73dRk6PHFq8dGFng8WywpXJYl4eNp4o/ZHXWyzPIuN2lLQzvFvlSxrjnyqyG4D8c4aWEJ2XDZ/CsOyxdPXja1EDW2NkPjSAyEEtyV+NzUlZzgEzE7NrqSsTW658HSS/3S3dl8RnXOp3EKEkNxRivyyAAMY/FPHr+omuQYSjdeUlamoh/u+lg71Ct1fm+2Y2IRnvhID0ZGNP0WVgAK0kPFwFs+MO1BBSrM/ifUNlp92YNDFjDklKV8rxo0iCpJ2zDnm6lt0rEdb5v9bhxwb9JaHjkNUQ+GKcPeVffyRbvPw='

