info:
  from: git
  name: syssms
  profile: dev
  pwd: {cipher}1920AQA6re35UlLsM+a0z4LUcJVMQzA5+jU1mIXnZvLZUrO06jh1jTBfcqVQFCBTnKRfST0+PLGUInSh01Yyy50gXJhLz73dRk6PHFq8dGFng8WywpXJYl4eNp4o/ZHXWyzPIuN2lLQzvFvlSxrjnyqyG4D8c4aWEJ2XDZ/CsOyxdPXja1EDW2NkPjSAyEEtyV+NzUlZzgEzE7NrqSsTW658HSS/3S3dl8RnXOp3EKEkNxRivyyAAMY/FPHr+omuQYSjdeUlamoh/u+lg71Ct1fm+2Y2IRnvhID0ZGNP0WVgAK0kPFwFs+MO1BBSrM/ifUNlp92YNDFjDklKV8rxo0iCpJ2zDnm6lt0rEdb5v9bhxwb9JaHjkNUQ+GKcPeVffyRbvPw=

spring:
  datasource:
    username: dbuser
    password: '{cipher}1920AQA6re35UlLsM+a0z4LUcJVMQzA5+jU1mIXnZvLZUrO06jh1jTBfcqVQFCBTnKRfST0+PLGUInSh01Yyy50gXJhLz73dRk6PHFq8dGFng8WywpXJYl4eNp4o/ZHXWyzPIuN2lLQzvFvlSxrjnyqyG4D8c4aWEJ2XDZ/CsOyxdPXja1EDW2NkPjSAyEEtyV+NzUlZzgEzE7NrqSsTW658HSS/3S3dl8RnXOp3EKEkNxRivyyAAMY/FPHr+omuQYSjdeUlamoh/u+lg71Ct1fm+2Y2IRnvhID0ZGNP0WVgAK0kPFwFs+MO1BBSrM/ifUNlp92YNDFjDklKV8rxo0iCpJ2zDnm6lt0rEdb5v9bhxwb9JaHjkNUQ+GKcPeVffyRbvPw='

