server:
  port: 8001 # https端口
  ssl:
      key-store: ${user.dir}/ssl-keys-dev.jks
      key-store-password: 701712
      key-password: 701712

---
custom:
  tomcat:
    http:
      port: 8000 # http端口
    redirect-flg: false # false表示打开http端口时不自动跳转到https

#---
#spring:
#  cloud:
#    config:
#      username: admin
#      password: 123456

#---
#spring:
#  rabbitmq:
#    host: 127.0.0.1
#    port: 15672
#    username: zmt
#    password: zmt123!
#    virtual-host: /

---
#eureka: #服务注册
#  instance:
##    prefer-ip-address: true
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:1111/eureka/

---
logging:
  config: classpath:dev/log4j2.xml

---
# cors跨域设置
custom:
  cors:
    mapping: /**
    allowCredentials: false
    allowedOrigins: "*" #允许的域，多个用逗号隔开。*允许全部的域通过。一定要用双引号，否则配置文件报错。
#    allowedMethods: POST,GET,DELETE,PUT #这样设置，静态资源将不能跨域
    allowedMethods: "*"
    allowedHeaders: "*"

---
### redis,rabbitmq
spring:
  profiles: redis-config-dev,rabbitmq-config-dev