server:
  port: 8001
  ssl:
      key-store: classpath:dev/mykeys.jks
      key-store-password: 701712
      key-password: 701712

#---
#spring:
#  cloud:
#    config:
#      username: admin
#      password: 123456

---
spring:
  rabbitmq:
    host: 119.23.78.160
    port: 5672
    username: zmt
    password: 701712
    virtual-host: /

---
#eureka: #服务注册
#  instance:
##    prefer-ip-address: true
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:1111/eureka/

---
logging:
  config: classpath:dev/log4j2.xml