server:
  port: 1111
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka-server1:1111/eureka/
    #不注册自己
    fetch-registry: false
    register-with-eureka: false